name: Build CPATracker

on:
  push:
    tags:
      - 'v*'   # Run workflow on version tags like v1.0, v1.1 etc.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      # Install Ninja for faster builds
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.0'

      - name: Configure & Build
        run: |
          mkdir build && cd build
          cmake .. -G Ninja -DCMAKE_PREFIX_PATH=$Qt6_DIR -DCMAKE_BUILD_TYPE=Release
          cmake --build .

      # Windows Deployment
      - name: Deploy Qt (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd build
          windeployqt CPATracker.exe

      # macOS Deployment
      - name: Deploy Qt (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          cd build
          macdeployqt CPATracker.app

      # Linux Deployment
      - name: Deploy Qt (Linux)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2 libxcb-cursor0
          wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          chmod +x linuxdeployqt-continuous-x86_64.AppImage
          ./linuxdeployqt-continuous-x86_64.AppImage build/CPATracker -appimage

      # Upload built artifacts
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CPATracker-${{ matrix.os }}
          path: |
            build/**/*.exe
            build/**/*.app
            build/**/*.AppImage
